---
name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Hugo
        run: |
          curl --location --remote-name --silent --remote-name hugo.deb "https://github.com/gohugoio/hugo/releases/download/v0.118.2/hugo_0.118.2_linux-amd64.deb"
          sudo apt install --quiet ./hugo.deb
          rm -f ./hugo.deb
      - name: Build Site
        run: hugo --cleanDestinationDir
      - name: Commit
        run: |
          git config user.email "majordomo@f3soil.com"
          git config user.name "GitHub Actions"
          git add ./docs
          if test -z "$(git status --porcelain)"
          then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Generate Site"
            git push
          fi
